import type { CropId } from '../types/ids'
import type { FormKey } from './crop-sprite-forms'

/**
 * What colour each crop is, and which shape it takes.
 *
 * The split between this file and `crop-sprite-forms.ts` is the whole reason 182 crops can be drawn
 * without 182 drawings: a form is a pixel grid of palette SLOTS, a palette is three colours, and a
 * crop is one of each. Carrot and parsnip are the same taproot in different colours. Tomato and
 * apple are the same round fruit, which is honest at 20px: nobody is being asked to tell those two
 * apart by shape, and the crop's own name is on the row beside it.
 *
 * These are illustrations and not evidence, which is why they may be authored at all. Every
 * FIGURE in this app traces to a source; a picture of a courgette being green traces to nothing
 * and claims nothing, and it is `aria-hidden` wherever it renders, so nothing here is ever read
 * out as though it were a finding. That is also the argument against photographs: a photograph
 * captioned "cucumber" IS a claim about a cultivar, grown somewhere, at some stage, and this
 * project has no citation for it.
 */

/** Body, shade and lit side. The leaf green in `g` is the same on almost everything and is set
 *  once in the renderer, so a palette is only the three colours that make a crop itself */
export interface SpritePalette {
  readonly a: string
  readonly b: string
  readonly c: string
}

/**
 * Mid-tone on purpose, every one of them. These sit on the panel background in both schemes, and
 * a palette pitched for white paper disappears against the dark one. Nothing here is dimmed with
 * opacity either, which is the trap this project has already been caught by once
 */
export const SPRITE_PALETTES = {
  tomato: { a: '#d94a3d', b: '#a8322a', c: '#ef7a63' },
  'pepper-red': { a: '#cf3630', b: '#9c2320', c: '#e87068' },
  aubergine: { a: '#6b4a8e', b: '#4a3163', c: '#9a76bc' },
  tomatillo: { a: '#7fb04a', b: '#5c8433', c: '#a6cf76' },
  cucumber: { a: '#3e7d3a', b: '#2a5828', c: '#67a85e' },
  courgette: { a: '#356b33', b: '#204a20', c: '#5d9a56' },
  'squash-tan': { a: '#c69a55', b: '#96702f', c: '#e0bd88' },
  pumpkin: { a: '#e07b2a', b: '#ac5716', c: '#f3a35c' },
  melon: { a: '#d9c07a', b: '#ab9450', c: '#eddaa4' },
  watermelon: { a: '#3f7a35', b: '#22491d', c: '#6fac5f' },
  okra: { a: '#6ba33f', b: '#4a7529', c: '#93c672' },
  'pod-green': { a: '#64a63e', b: '#46782a', c: '#8fc968' },
  'pod-pale': { a: '#a8c66a', b: '#7c9445', c: '#c8de96' },
  'pod-tan': { a: '#c9b06a', b: '#9a8342', c: '#e2d09c' },
  'grain-gold': { a: '#d9b45e', b: '#a8873a', c: '#efd694' },
  'grain-pale': { a: '#e0d09a', b: '#ac9c67', c: '#f4ecc8' },
  'grain-red': { a: '#c0563f', b: '#8e3a29', c: '#dc8871' },
  corn: { a: '#f0c53e', b: '#bd9420', c: '#ffe07a' },
  potato: { a: '#c49a63', b: '#96703f', c: '#ddbb8c' },
  'sweet-potato': { a: '#c2683f', b: '#93482a', c: '#de9169' },
  carrot: { a: '#e07a26', b: '#ab5514', c: '#f4a45c' },
  parsnip: { a: '#e2d6a8', b: '#ad9f6f', c: '#f4eed6' },
  beet: { a: '#9c3a63', b: '#6f2444', c: '#c26389' },
  radish: { a: '#d33f52', b: '#9f2637', c: '#ea7484' },
  turnip: { a: '#d5cfe2', b: '#9e98b2', c: '#efecf6' },
  celeriac: { a: '#cbbfa3', b: '#978c72', c: '#e6ddc9' },
  kohlrabi: { a: '#a9c98a', b: '#7b9760', c: '#c9e2b1' },
  onion: { a: '#c9974f', b: '#99682c', c: '#e2bb82' },
  garlic: { a: '#e6e0d4', b: '#aca596', c: '#f7f4ee' },
  leek: { a: '#9dc36a', b: '#6f9243', c: '#c3dd97' },
  celery: { a: '#a8c86a', b: '#7b9646', c: '#c9e196' },
  rhubarb: { a: '#cf4a5c', b: '#9b3040', c: '#e88094' },
  asparagus: { a: '#6f9c4a', b: '#4e7130', c: '#99c477' },
  fennel: { a: '#d7e0a8', b: '#a3ab74', c: '#eef2d4' },
  'leaf-bright': { a: '#7cc04a', b: '#57912f', c: '#a5dc7a' },
  'leaf-deep': { a: '#3f8a3e', b: '#255c25', c: '#68ad63' },
  'leaf-blue': { a: '#5f9a7e', b: '#3f7057', c: '#8bbfa4' },
  'leaf-grey': { a: '#8fa877', b: '#677f51', c: '#b2c79e' },
  'leaf-red': { a: '#a8455e', b: '#7a2c40', c: '#c87d90' },
  'leaf-pale': { a: '#c3d798', b: '#96a96c', c: '#dfeac0' },
  'herb-green': { a: '#4e9b45', b: '#357030', c: '#7fc072' },
  'herb-blue': { a: '#5c8f6e', b: '#3d6449', c: '#87b596' },
  'herb-grey': { a: '#8ba07e', b: '#647a58', c: '#aebfa4' },
  'herb-purple': { a: '#8a5a86', b: '#603c5d', c: '#af86ab' },
  strawberry: { a: '#dc3b47', b: '#a3242f', c: '#f0737c' },
  raspberry: { a: '#c8425f', b: '#963049', c: '#e0748a' },
  blackberry: { a: '#4a3552', b: '#2b1d33', c: '#7b6084' },
  blueberry: { a: '#5877b0', b: '#3d5580', c: '#8aa4d2' },
  'berry-red': { a: '#c8323f', b: '#94212c', c: '#e26e78' },
  gooseberry: { a: '#b7cc72', b: '#8a9c4c', c: '#d5e5a4' },
  grape: { a: '#7b5292', b: '#573768', c: '#a681bb' },
  apple: { a: '#cf3f42', b: '#9c2a2d', c: '#e87b7c' },
  pear: { a: '#c9c85a', b: '#97962f', c: '#e2e18e' },
  peach: { a: '#eb9a5e', b: '#b96f37', c: '#f8c194' },
  plum: { a: '#7a4a86', b: '#56305f', c: '#a97cb4' },
  apricot: { a: '#e8a942', b: '#b47a20', c: '#f6cd85' },
  fig: { a: '#6f4a72', b: '#4c3050', c: '#9d7ea0' },
  'nut-brown': { a: '#a9784a', b: '#7d552f', c: '#c99e73' },
  hops: { a: '#a9c76a', b: '#7b9445', c: '#c9e099' },
  kiwi: { a: '#8a9b4a', b: '#647030', c: '#b0bd7c' },
  'flower-yellow': { a: '#f0c53e', b: '#bd9420', c: '#ffe07a' },
  'flower-orange': { a: '#ef8f36', b: '#b96520', c: '#f9b571' },
  'flower-white': { a: '#eeece2', b: '#b4b2a6', c: '#fbfaf5' },
  'flower-blue': { a: '#5b76c4', b: '#3f5493', c: '#8fa3e0' },
  'flower-violet': { a: '#7f6cc0', b: '#5a4a8f', c: '#a99cd8' },
  'flower-pink': { a: '#d96a94', b: '#a3486c', c: '#eda0b9' },
  'flower-crimson': { a: '#c93a4e', b: '#96253a', c: '#e37a89' },
  'grass-green': { a: '#6ba54a', b: '#4a7830', c: '#93c674' },
  'grass-tall': { a: '#8fae5a', b: '#68843a', c: '#b4cd8c' },
} as const satisfies Record<string, SpritePalette>

export type PaletteKey = keyof typeof SPRITE_PALETTES

/**
 * Every crop in the catalogue, as a form and a palette.
 *
 * Total, and `crop-sprite.test.ts` holds it against `CROP_ROWS` rather than against this file, so
 * a crop added to the catalogue fails here rather than shipping without a picture. Until somebody
 * draws it, `CropPicture` falls back to the class silhouette, so a missing entry is a plainer
 * drawing and never a hole.
 *
 * The order follows the catalogue's own, which groups by what a thing is, so anyone can read
 * the two side by side
 */
export const CROP_SPRITE: Readonly<Record<string, readonly [FormKey, PaletteKey]>> = {
  tomato: ['round-fruit', 'tomato'],
  'pepper-sweet': ['teardrop-fruit', 'pepper-red'],
  'pepper-hot': ['long-fruit', 'pepper-red'],
  eggplant: ['teardrop-fruit', 'aubergine'],
  tomatillo: ['round-fruit', 'tomatillo'],
  cucumber: ['long-fruit', 'cucumber'],
  'squash-summer': ['long-fruit', 'courgette'],
  'squash-winter': ['round-fruit', 'squash-tan'],
  pumpkin: ['round-fruit', 'pumpkin'],
  melon: ['round-fruit', 'melon'],
  watermelon: ['round-fruit', 'watermelon'],
  okra: ['long-fruit', 'okra'],
  'bean-bush': ['pod', 'pod-green'],
  'bean-pole': ['pod', 'pod-green'],
  'bean-runner': ['pod', 'pod-green'],
  'pea-garden': ['pod', 'pod-pale'],
  'fava-bean': ['pod', 'pod-pale'],
  cowpea: ['pod', 'pod-tan'],
  'soybean-edamame': ['pod', 'pod-pale'],
  lentil: ['pod', 'pod-tan'],
  chickpea: ['pod', 'pod-tan'],
  peanut: ['nut', 'pod-tan'],
  'sweet-corn': ['cob', 'corn'],
  'wheat-spring': ['ear', 'grain-gold'],
  barley: ['ear', 'grain-gold'],
  oat: ['ear', 'grain-pale'],
  'rye-cereal': ['ear', 'grain-pale'],
  quinoa: ['ear', 'grain-red'],
  'amaranth-grain': ['ear', 'grain-red'],
  goosefoot: ['ear', 'grain-pale'],
  sumpweed: ['ear', 'grain-pale'],
  potato: ['tuber', 'potato'],
  'sweet-potato': ['tuber', 'sweet-potato'],
  carrot: ['taproot', 'carrot'],
  beet: ['round-root', 'beet'],
  radish: ['round-root', 'radish'],
  turnip: ['round-root', 'turnip'],
  rutabaga: ['round-root', 'celeriac'],
  parsnip: ['taproot', 'parsnip'],
  celeriac: ['round-root', 'celeriac'],
  kohlrabi: ['round-root', 'kohlrabi'],
  'jerusalem-artichoke': ['tuber', 'sweet-potato'],
  horseradish: ['taproot', 'parsnip'],
  'onion-bulb': ['bulb', 'onion'],
  shallot: ['bulb', 'onion'],
  garlic: ['bulb', 'garlic'],
  leek: ['stalks', 'leek'],
  scallion: ['stalks', 'leek'],
  chives: ['grass', 'herb-green'],
  'lettuce-leaf': ['leafy-bunch', 'leaf-bright'],
  'lettuce-head': ['head', 'leaf-bright'],
  spinach: ['leafy-bunch', 'leaf-deep'],
  'swiss-chard': ['leafy-bunch', 'leaf-deep'],
  kale: ['leafy-bunch', 'leaf-blue'],
  collards: ['leafy-bunch', 'leaf-grey'],
  'mustard-greens': ['leafy-bunch', 'leaf-bright'],
  arugula: ['leafy-bunch', 'leaf-deep'],
  mizuna: ['leafy-bunch', 'leaf-bright'],
  tatsoi: ['leafy-bunch', 'leaf-deep'],
  'bok-choy': ['stalks', 'leaf-pale'],
  endive: ['leafy-bunch', 'leaf-pale'],
  radicchio: ['head', 'leaf-red'],
  celery: ['stalks', 'celery'],
  'nz-spinach': ['leafy-bunch', 'leaf-deep'],
  sorrel: ['leafy-bunch', 'leaf-bright'],
  mache: ['leafy-bunch', 'leaf-bright'],
  claytonia: ['leafy-bunch', 'leaf-pale'],
  watercress: ['leafy-bunch', 'leaf-deep'],
  orach: ['leafy-bunch', 'leaf-red'],
  purslane: ['leafy-bunch', 'leaf-bright'],
  'good-king-henry': ['leafy-bunch', 'leaf-deep'],
  'sea-kale': ['leafy-bunch', 'leaf-blue'],
  cabbage: ['head', 'leaf-grey'],
  broccoli: ['floret', 'leaf-deep'],
  cauliflower: ['floret', 'flower-white'],
  'brussels-sprouts': ['stalks', 'leaf-grey'],
  'napa-cabbage': ['head', 'leaf-pale'],
  romanesco: ['floret', 'leaf-bright'],
  basil: ['herb-sprig', 'herb-green'],
  parsley: ['herb-sprig', 'herb-green'],
  cilantro: ['herb-sprig', 'herb-green'],
  dill: ['herb-sprig', 'herb-blue'],
  mint: ['herb-sprig', 'herb-green'],
  oregano: ['herb-sprig', 'herb-grey'],
  thyme: ['herb-sprig', 'herb-grey'],
  rosemary: ['herb-sprig', 'herb-blue'],
  sage: ['herb-sprig', 'herb-grey'],
  tarragon: ['herb-sprig', 'herb-green'],
  'lemon-balm': ['herb-sprig', 'herb-green'],
  lovage: ['herb-sprig', 'herb-green'],
  marjoram: ['herb-sprig', 'herb-grey'],
  'fennel-bulb': ['stalks', 'fennel'],
  shiso: ['herb-sprig', 'herb-purple'],
  chervil: ['herb-sprig', 'herb-green'],
  'summer-savory': ['herb-sprig', 'herb-grey'],
  'bay-laurel': ['herb-sprig', 'leaf-deep'],
  'winter-savory': ['herb-sprig', 'herb-grey'],
  hyssop: ['herb-sprig', 'herb-blue'],
  'anise-hyssop': ['herb-sprig', 'herb-purple'],
  strawberry: ['berry-heart', 'strawberry'],
  raspberry: ['berry-cluster', 'raspberry'],
  blackberry: ['berry-cluster', 'blackberry'],
  blueberry: ['berry-cluster', 'blueberry'],
  lingonberry: ['berry-cluster', 'berry-red'],
  'lowbush-blueberry': ['berry-cluster', 'blueberry'],
  cranberry: ['berry-cluster', 'berry-red'],
  teaberry: ['berry-cluster', 'berry-red'],
  sweetfern: ['herb-sprig', 'herb-grey'],
  'currant-red': ['berry-cluster', 'berry-red'],
  'currant-black': ['berry-cluster', 'blackberry'],
  gooseberry: ['berry-cluster', 'gooseberry'],
  elderberry: ['berry-cluster', 'grape'],
  rhubarb: ['stalks', 'rhubarb'],
  asparagus: ['stalks', 'asparagus'],
  'globe-artichoke': ['head', 'leaf-blue'],
  grape: ['berry-cluster', 'grape'],
  apple: ['round-fruit', 'apple'],
  pear: ['teardrop-fruit', 'pear'],
  peach: ['round-fruit', 'peach'],
  plum: ['round-fruit', 'plum'],
  'cherry-sweet': ['berry-cluster', 'apple'],
  'cherry-sour': ['berry-cluster', 'berry-red'],
  apricot: ['round-fruit', 'apricot'],
  fig: ['teardrop-fruit', 'fig'],
  hazelnut: ['nut', 'nut-brown'],
  pawpaw: ['teardrop-fruit', 'pear'],
  serviceberry: ['berry-cluster', 'plum'],
  aronia: ['berry-cluster', 'blackberry'],
  'hardy-kiwi': ['teardrop-fruit', 'kiwi'],
  hops: ['teardrop-fruit', 'hops'],
  crabapple: ['round-fruit', 'apple'],
  'highbush-cranberry': ['berry-cluster', 'berry-red'],
  'wild-ginger': ['leafy-bunch', 'leaf-deep'],
  ramps: ['stalks', 'leaf-bright'],
  enset: ['leafy-bunch', 'leaf-bright'],
  // the tropical and subtropical staples added 2026-09-12: what each is grown for, in the
  // form that reads at a glance from the camera's height
  cassava: ['tuber', 'sweet-potato'],
  taro: ['leafy-bunch', 'leaf-deep'],
  'yam-greater': ['tuber', 'potato'],
  plantain: ['leafy-bunch', 'leaf-bright'],
  'rice-upland': ['ear', 'grain-pale'],
  lemon: ['round-fruit', 'corn'],
  mango: ['teardrop-fruit', 'apricot'],
  papaya: ['teardrop-fruit', 'pumpkin'],
  'pigeon-pea': ['pod', 'pod-tan'],
  sesame: ['pod', 'pod-pale'],
  moringa: ['pod', 'pod-green'],
  'marigold-french': ['flower', 'flower-orange'],
  'marigold-african': ['flower', 'flower-yellow'],
  nasturtium: ['flower', 'flower-orange'],
  borage: ['flower', 'flower-blue'],
  calendula: ['flower', 'flower-orange'],
  sunflower: ['flower', 'flower-yellow'],
  buckwheat: ['flower', 'flower-white'],
  'clover-crimson': ['flower', 'flower-crimson'],
  'clover-white': ['flower', 'flower-white'],
  'clover-red': ['flower', 'flower-pink'],
  phacelia: ['flower', 'flower-violet'],
  'sweet-alyssum': ['flower', 'flower-white'],
  yarrow: ['flower', 'flower-white'],
  'ryegrass-perennial': ['grass', 'grass-green'],
  'vetch-hairy': ['pod', 'pod-pale'],
  'field-pea': ['pod', 'pod-pale'],
  'mustard-cover': ['flower', 'flower-yellow'],
  'sorghum-sudangrass': ['ear', 'grain-red'],
  desmodium: ['leafy-bunch', 'leaf-grey'],
  'napier-grass': ['grass', 'grass-tall'],
  comfrey: ['leafy-bunch', 'leaf-blue'],
  fenugreek: ['pod', 'pod-pale'],
  'bergamot-wild': ['flower', 'flower-violet'],
  'cup-plant': ['flower', 'flower-yellow'],
  boneset: ['flower', 'flower-white'],
  'lanceleaf-coreopsis': ['flower', 'flower-yellow'],
  'canada-anemone': ['flower', 'flower-white'],
  murnong: ['taproot', 'parsnip'],
}

export const spriteFor = (cropId: CropId): readonly [FormKey, PaletteKey] | undefined =>
  CROP_SPRITE[String(cropId)]
