// GENERATED by scripts/generate-rust-tables.mjs from src/sim/perez-tables.ts
// Do not edit. Edit the TypeScript and re-run `bun run generate`.
//
// Perez, Ineichen, Seals, Michalsky & Stewart 1990, Solar Energy 44(5) 271-289.
// Eight sky-clearness bins by six F coefficients, and the lower edges that select a bin.

#[rustfmt::skip]
pub static PEREZ_1990_ALLSITES: &[[f64; 6]] = &[
    [-0.008, 0.588, -0.062, -0.06, 0.072, -0.022],
    [0.13, 0.683, -0.151, -0.019, 0.066, -0.029],
    [0.33, 0.487, -0.221, 0.055, -0.064, -0.026],
    [0.568, 0.187, -0.295, 0.109, -0.152, -0.014],
    [0.873, -0.392, -0.362, 0.226, -0.462, 0.001],
    [1.132, -1.237, -0.412, 0.288, -0.823, 0.056],
    [1.06, -1.6, -0.359, 0.264, -1.127, 0.131],
    [0.678, -0.327, -0.25, 0.156, -1.377, 0.251],
];

#[rustfmt::skip]
pub static PEREZ_EPSILON_EDGES: &[f64] = &[1.065, 1.23, 1.5, 1.95, 2.8, 4.5, 6.2];
